invoke some functions in Commit method after save changes
BSVN/Commons pull request #4
Opened 2019-11-27 09:53 UTC by Mistogan1991

میخواهیم فانکشن هایی از قبیل کار با فایل سیستم ها در صورت نیاز به داخل صفی اظافه شوند و بعد از اینکه تغییرات دیتا بیس ذخیره شد اجزا شوند
و اگر هنگام اجرا شدن این فانکشن ها با مشکلی مواجه شدیم بتوانیم دیتا بیس را به حالت اولیه باز گردانیم

2019-12-04 15:31 UTC, soroshsabz commented
ITNOA

@Mistogan1991 Why test is failed? please see appveyor log for detailed

2019-12-04 15:49 UTC, soroshsabz requested changes

2019-12-04 15:49 UTC, soroshsabz commented on Source/BSN.Commons/Infrastructure/UnitOfWork.cs
> +        public List<Exception> _exceptions { get; set; }
What is this?

2019-12-04 15:49 UTC, soroshsabz commented on Source/BSN.Commons/Infrastructure/UnitOfWork.cs
> +            if (task == null)
Please use ?? operator for null checking

2019-12-04 15:49 UTC, soroshsabz commented on Source/BSN.Commons/Infrastructure/UnitOfWork.cs
> +        private readonly IDatabaseFactory _databaseFactory;
Please add private member in end of class

2019-12-04 15:49 UTC, soroshsabz commented on Source/BSN.Commons/Infrastructure/UnitOfWork.cs
> +            if (executeFunction == null)
Please use ?? operator

2019-12-04 15:49 UTC, soroshsabz commented on Source/BSN.Commons/Infrastructure/UnitOfWork.cs
> +        public void AddToQueue(Task executeFunction, Task rollbackFunction)
Why you don't use ITaskUnit? what is beneficiary?

2019-12-04 15:49 UTC, soroshsabz commented on Source/BSN.Commons/Infrastructure/UnitOfWork.cs
> +                    if (task.Exception != null)
Are you sure to the task capture all exceptions?

2019-12-04 15:49 UTC, soroshsabz commented on Source/BSN.Commons/Infrastructure/UnitOfWork.cs
> +            using (var transaction = new TransactionScope())
if all exception catch by task, why are using TransactionScope?

2019-12-04 15:49 UTC, soroshsabz commented on Source/BSN.Commons/Infrastructure/UnitOfWork.cs
> +                        _exceptions.Add(task.Exception);
??

2019-12-08 15:06 UTC, GreenCodeLine reviewed
لطفا موارد ذکر شده بررسی گردد

2019-12-08 15:06 UTC, GreenCodeLine commented on Source/BSN.Commons/BSN.Commons.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="3.1.0" />
آیا از این پکیج استفاده شده؟
در صورتی که استفاده نمیکنید حذف شود و موارد مشابه

2019-12-08 15:06 UTC, GreenCodeLine commented on Source/BSN.Commons/Infrastructure/IUnitOfWork.cs
> +        void AddToQueue(Task task, Task rollback);
این اور لود درست نیست
قبلا توضیح داده شده بود

2019-12-09 09:41 UTC, merged