Add AutoMapper extension
BSVN/Commons pull request #84
Opened 2024-05-06 11:04 UTC by Reza-Noei

Please review this PR 🌹

2024-05-06 14:41 UTC, soroshsabz commented
Please add README.md to explain how to use it in client projects

2024-05-06 14:42 UTC, soroshsabz commented on Source/BSN.Commons.AutoMapper/BSN.Commons.AutoMapper.csproj
> +  <PropertyGroup>
Please add packaing information (like other commons project)

2024-05-06 14:44 UTC, soroshsabz commented on Source/BSN.Commons.AutoMapper/BSN.Commons.AutoMapper.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Please update cake for building and packaing this project correctly

2024-05-06 14:46 UTC, soroshsabz commented on Source/BSN.Commons.AutoMapper/Extensions/IServiceCollectionExtensions.cs
> +namespace BSN.Commons.AutoMapper.Extensions
Please add some test project to ensure this behavior work correctly with downstream AutoMapper profiles.

2024-05-06 14:47 UTC, soroshsabz requested changes
Please see comments and resolve it

2024-05-15 11:35 UTC, soroshsabz approved these changes

2024-05-15 11:39 UTC, soroshsabz requested changes

2024-05-15 11:39 UTC, soroshsabz commented on Source/BSN.Commons.AutoMapper/README.md
> +AutoMapper is a popular library for mapping objects from one type to another. It simplifies the process of mapping complex objects and reduces the amount of code needed to perform these mappings.
Please add explicitly description of supported mapping complex types currently.

2024-05-15 11:39 UTC, soroshsabz commented on Test/BSN.Commons.AutoMapper.Tests/CommonMapperProfileTests .cs
> +    public class CommonMapperProfileTests
Please add one another test, that shows working this AutoMapper helper with additional custom AutoMapper profile

2024-05-15 11:39 UTC, soroshsabz commented
@MostafaFarajbakhsh

2024-06-29 12:41 UTC, Reza-Noei reviewed
Code reviewed.

2024-06-29 12:44 UTC, Reza-Noei reviewed
Code successfully reviewed.

2024-06-29 16:08 UTC, soroshsabz approved these changes

2024-06-29 16:08 UTC, merged