Update to version 1.17.0
BSVN/Commons pull request #93
Opened 2024-10-14 05:39 UTC by meghasemim1999

2024-10-18 19:06 UTC, soroshsabz requested changes

2024-10-18 19:06 UTC, soroshsabz commented on Source/BSN.Commons/CHANGELOG.md
> +## [1.17.0] - 2024-10-14
Please update changelog

2024-10-19 08:07 UTC, meghasemim1999 commented on Source/BSN.Commons/CHANGELOG.md
> +## [1.17.0] - 2024-10-14
Done

2024-11-07 11:44 UTC, soroshsabz approved these changes

2024-11-07 11:44 UTC, merged